/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tekuto1s (https://sketchfab.com/tekuto1s)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-robotic-arm-0a7906d34fd245468e6734062b914715
Title: Sci Fi Robotic Arm
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import robotScene from "../assets/sci_fi_robotic_arm.glb";
import { a } from "@react-spring/three";
const RobotArm = (props) => {
  const robotRef = useRef(null);
  const { nodes, materials } = useGLTF(robotScene);
  return (
    <group
      {...props}
      dispose={null}
      ref={robotRef}
    >
      <group position={[0, 0.237, 0]}>
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.metal_dark}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.metal}
        />
      </group>
      <group
        position={[0, 14.335, -8.618]}
        rotation={[0.611, 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.material_0}
        />
        <group
          position={[0, -8.951, -18.928]}
          rotation={[0.175, 0, -Math.PI / 2]}
          scale={[1, 0.69, 1]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_36.geometry}
            material={materials.metal_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_38.geometry}
            material={materials.plastic}
            scale={[1, 0.993, 1]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials.metal}
          position={[0, -2.953, -16.929]}
          rotation={[-1.309, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.metal_dark}
          position={[0, 2.127, -15.528]}
          rotation={[3.054, 0, -Math.PI / 2]}
          scale={0.629}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials.metal}
          position={[0, 2.127, -15.528]}
          rotation={[3.054, 0, -Math.PI / 2]}
          scale={0.617}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_40.geometry}
          material={materials.metal}
          position={[0, -8.951, -18.928]}
          rotation={[0.175, 0, -Math.PI / 2]}
          scale={[1, 0.69, 1]}
        />
      </group>
      <group position={[0, 0.237, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_53.geometry}
          material={materials.material_0}
        />
      </group>
      <group
        position={[-5.267, 0, -9.122]}
        rotation={[0, Math.PI / 6, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_61.geometry}
          material={materials.metal_dark}
        />
        <group position={[0, -0.538, -3.842]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_63.geometry}
            material={materials.metal_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_64.geometry}
            material={materials.material_0}
          />
          <group position={[0, -0.544, -0.336]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_66.geometry}
              material={materials.metal_dark}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_68.geometry}
              material={materials.metal_dark}
              position={[0.579, 0.005, 0]}
            />
          </group>
        </group>
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.metal_dark}
        position={[0, 0.237, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.metal_dark}
        position={[-3.025, 0.264, -5.503]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.metal_dark}
        position={[0, 0.237, 0]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.metal_dark}
        position={[0, 6.383, 0]}
        scale={0.921}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.metal_dark}
        position={[0, 6.383, 0]}
        scale={0.921}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.metal}
        position={[0, 6.383, 0]}
        scale={0.921}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials.metal}
        position={[0, 6.383, 0]}
      />
      <mesh
        geometry={nodes.Object_21.geometry}
        material={materials.metal}
        position={[0, 6.383, 0]}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials.metal_dark}
        position={[0, 14.335, -8.618]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 1.394, 1]}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials.metal}
        position={[0, 14.335, -8.618]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.981, 1.367, 0.981]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.plastic}
        position={[1.939, 5.726, 6.244]}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.metal_lighter}
        position={[1.939, 5.726, 6.244]}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.metal_dark}
        position={[0, 18.162, -32.122]}
        rotation={[-0.464, 0, 0]}
        scale={[0.69, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.metal_dark}
        position={[0, 15.72, -31.05]}
        rotation={[-0.315, 0, Math.PI]}
        scale={[0.69, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.plastic}
        position={[0, 19.49, 9.871]}
      />
      <mesh
        geometry={nodes.Object_55.geometry}
        material={materials.metal_dark}
        position={[0, 6.383, 0]}
        scale={0.921}
      />
      <mesh
        geometry={nodes.Object_57.geometry}
        material={materials.text}
        position={[0, 0.237, -0.007]}
      />
      <mesh
        geometry={nodes.Object_59.geometry}
        material={materials.text2}
        position={[4.392, 8.026, 6.028]}
        scale={[1, 0.236, 1]}
      />
    </group>
  );
};

export default RobotArm;
